### PR TITLE
Add `clangsa` pass to `analyzegc` run

### PR DESCRIPTION
**Pull request by staticfloat**
@keno I believe this is what you asked for?

### CODE REVIEW

**Comment by Keno** [comment]
Yes, thank you!. Though now I'm wondering if we need to build the plugin first. I'm not sure the test target has the dependency set up. Though maybe it should.

**Comment by Keno** [comment]
https://github.com/JuliaLang/julia/pull/37385

**Comment by staticfloat** [comment]
> JuliaLang/julia#37385

Now that that's merged, I'm going to merge this and kick off a dummy PR to ensure it runs properly.

**Comment by Keno** [comment]
The self tests care currently broken, which will be fixed by https://github.com/JuliaLang/julia/pull/37366. I guess I'll go merge that.

**Pull request merged**
