### PR TITLE
Use `rr` to run Julia tests

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by vchuravy** [comment]
We should run rr under chaos mode for the multi-threading tests.

**Comment by staticfloat** [comment]
I hear that has a big performance impact. :/

**Comment by vchuravy** [comment]
Yeah. then we should run only the multi-threading tests under `-h` otherwise what's the point

**Comment by staticfloat** [comment]
For reproducibility of everything else; It would be good to do that, let's see how much performance impact the rest of the `rr` stuff adds.  I know Keno's done a lot of work to try and get `rr` fast enough to run everything inside of it. :)

**Pull request merged**
