### PR TITLE
Try adding an old branch canceller plugin

### PR DESCRIPTION
**Pull request by staticfloat**
We want to cancel old builds on PRs but not on `master`, since we'd like to have a list of green checkmarks

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@staticfloat Looks like the auto reload failed?

https://build.julialang.org/#/builders/34

**Comment by DilumAluthge** [comment]
Could you check the twistd logs and see if there is a more useful error message there?

**Comment by staticfloat** [comment]
It just took a long time, I think.

**Comment by DilumAluthge** [comment]
Hmmmm.

**Comment by DilumAluthge** [comment]
But as a result, the auto-retry functionality doesn't seem to be deployed. See e.g. https://github.com/JuliaLang/julia/pull/43033

**Pull request merged**
