### PR TITLE
Add signing of internal `julia.exe`

### PR DESCRIPTION
**Pull request by staticfloat**
@ViralBShah this should address the feedback we got at JuliaCon

### CODE REVIEW

**Comment by ararslan** [comment]
For those of us not in the know, can you explain what the feedback was and what this change does?

**Comment by ViralBShah** [comment]
See the referenced issue above for the background.

**Comment by staticfloat** [comment]
Linking explicitly so as not to rely on Github's linkage stuff: https://github.com/JuliaLang/julia/issues/25730

**Comment by ararslan** [comment]
Very nice, thanks guys

**Pull request merged**
