### PR TITLE
Actually add the `OldBuildCanceller` to the list of services

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@staticfloat It is with this change that the auto-reload fails. See e.g. https://build.julialang.org/#/builders/34/builds/66

The failure is deterministic, in the sense that I keep re-running it, and it fails every time.

**Comment by staticfloat** [comment]
Yeah I dunno.  I tried reloading it from scratch, and it seems to have worked.

**Comment by DilumAluthge** [comment]
What is "reloading it from scratch"?

**Comment by staticfloat** [comment]
Killing the buildbot and restarting it, rather than reloading while the old process is still running.

**Comment by staticfloat** [comment]
Okay, watching the console as you just caused it to reconfig; it appears that it successfully finishes reconfiguring..... after 21 seconds.  So because it takes so long, it always reports it as a failure.

**Comment by DilumAluthge** [comment]
Ah I see.

So, the tricky part here is that even after you killed and restarted the Buildbot, the auto-reload still fails. E.g. https://build.julialang.org/#/builders/34/builds/68

So whenever we make future changes to this repo, we'll need to manually kill and restart the Buildbot to deploy the changes. (Because the auto-reload won't work.)

I think that mild inconvenience is still worth the benefit of the better resource management we get with auto-canceling old PR jobs. But it is slightly inconvenient.

**Comment by staticfloat** [comment]
Although the auto reload job reports failure, I believe it's actually working.  The logs say "reconfigure successful after 21s", so I think it's just that the webui shows the timeout.  We can probably adjust the timeout as well.

**Comment by DilumAluthge** [comment]
> We can probably adjust the timeout as well.

Ah, that seems like the path of least resistance.

Maybe make it 30 seconds?

Is this timeout something that I can do with a PR to this repo? Or does it need to be done on the Buildbot machine itself?

**Comment by DilumAluthge** [comment]
> > We can probably adjust the timeout as well.
> 
> That seems like the path of least resistance!
> 
> Maybe make it 30 seconds?
> 
> Is this timeout something that I can do with a PR to this repo? Or does it need to be done on the Buildbot machine itself?

See #250 and #251

**Pull request merged**
