### PR TITLE
Add Windows signing again

### PR DESCRIPTION
**Pull request by staticfloat**
@ararslan :)

### CODE REVIEW

**Comment by ararslan** [comment]
Wait seriously?? WHOA

**Comment by staticfloat** [comment]
I think it was merged too late for the 1.3-alpha binaries, but feel free to kick off some other random ones and see if they work.  :D

**Comment by staticfloat** [comment]
Also, these won't fail silently; if we aren't signing properly, that bubble will go red (the build will still go through though, so as not to annoy PR writers)

**Comment by staticfloat** [comment]
BTW, do you do Linux signing?  We could automatically upload GPG signatures as well, if that would be helpful.

**Comment by ararslan** [comment]
Yeah I do that manually as well for all of the Linux and FreeBSD binaries.

**Comment by staticfloat** [comment]
Okay we should be getting `.asc` files spat out right next to all the `.tar.gz` files as well.  This one's a little weird because I have to move them around alongside the `.tar.gz` files, so we'll let things settle for a little bit to ensure that it's all working as expected.

**Pull request merged**
